apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.crd.plural | lower -}}.{{- .Values.crd.group }}
spec:
  group: {{ .Values.crd.group }}
  versions:
    - name: {{ .Values.crd.version }}
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: {{ .Values.crd.plural }}
    singular: {{ .Values.crd.kind | lower }}
    kind: {{ .Values.crd.kind | title }}
    shortNames: []
