apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "buck.fullname" . }}
  labels:
{{ include "buck.labels" . | indent 4 }}

{{ if .Values.enableRBAC }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "buck.fullname" . }}
  labels:
{{ include "buck.labels" . | indent 4 }}
rules:
- apiGroups: ["", "apps", "batch", "extensions", "apiextensions.k8s.io", "{{ .Values.crd.group }}"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "buck.fullname" . }}
  labels:
{{ include "buck.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "buck.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "buck.fullname" . }}
  apiGroup: ""
{{ end }}
